workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - binaries
  - check
  - docs
  - publish

include:
  - component: $CI_SERVER_FQDN/connect2x/meta/create-mr-discussions@main
    inputs:
      token: $MR_DISCUSSIONS_TOKEN

binaries:
  stage: binaries
  tags: [ "mac","arm64","shell","small" ]
  artifacts:
    paths:
      - libsqlitenity/archive
      - libsqlitenity/lib
  script: cd libsqlitenity && ./ci.nu

check:
  stage: check
  tags: [ "mac","arm64","shell","small" ]
  cache:
    - paths: [ $GRADLE_USER_HOME ]
  artifacts:
    paths: [ "**/build/reports" ]
    reports:
      junit: "**/build/test-results/**/TEST-*.xml"
    when: always
  script: ./gradlew --stacktrace check

docs:
  stage: docs
  tags: [ "mac","shell","small" ]
  artifacts:
    name: docs
    when: always
    paths: [ build/dokka/html ]
    expire_in: 7d
  environment:
    name: docs/${CI_PIPELINE_IID}
    url: https://connect2x.gitlab.io/-/sqlitenity/-/jobs/${CI_JOB_ID}/artifacts/build/dokka/html/index.html
  script: ./gradlew --stacktrace dokkaGenerate

publish:
  stage: publish
  tags: [ "mac","shell","small" ]
  timeout: 2h
  cache:
    - paths: [ $GRADLE_USER_HOME ]
  script: ./gradlew --stacktrace publish
