# UnlockExperimentalVMOptions: needed for other args
# UseShenandoahGC: new GC that supports properly yielding memory back to the OS
# ShenandoahUncommit: the feature that yields memory back to the OS
# ShenandoahUncommitDelay: when to give back memory to the OS (milliseconds)
# TrimNativeHeapInterval: when to clean native heap (milliseconds)
# ShenandoahGuaranteedGCInterval: when to do a guaranteed GC (milliseconds)
# enable-native-access: needed because kotlin native uses Unsafe and newer JVM versions do not allow this
org.gradle.jvmargs=-XX:+UnlockExperimentalVMOptions \
                   -XX:+UseShenandoahGC \
                   -XX:+ShenandoahUncommit \
                   -XX:ShenandoahUncommitDelay=30000 \
                   -XX:TrimNativeHeapInterval=60000 \
                   -XX:ShenandoahGuaranteedGCInterval=300000

# See https://docs.gradle.org/current/userguide/build_environment.html#gradle_properties_reference
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=false
kotlin.compiler.execution.strategy=in-process

# See https://kotlinlang.org/docs/build-tools-api.html
# Not possible yet as only jvm is supported kotlin js
# kotlin.compiler.runViaBuildToolsApi=true

# See https://kotlinlang.org/docs/native-improving-compilation-time.html#try-incremental-compilation-of-klib-artifacts
kotlin.incremental.native=true
kotlin.native.parallelThreads=8

# See https://docs.gradle.org/current/userguide/isolated_projects.html
# TODO for deps (observed from testing):
#   - Kotlin Multplatform Web: https://youtrack.jetbrains.com/issue/KT-75899/Support-Gradle-Project-Isolation-in-KGP-JS-Wasm
#   - Mokkery: cannot dynamically look up a property in the parent project: dev.mokkery.gradle.MokkeryGradlePlugin.checkKotlinSetup(MokkeryGradlePlugin.kt:105)
#   - Ksp: cannot access task dependencies directly: com.google.devtools.ksp.gradle.KspSubpluginKt.nonSelfDeps(KspSubplugin.kt:960)
# org.gradle.unsafe.isolated-projects=true
# org.gradle.configuration-cache.max-problems=1000000
# kotlin.kmp.isolated-projects.support=enable
# org.gradle.unsafe.configuration-cache-problems=warn

# See https://kotlinlang.org/docs/code-style-migration-guide.html#in-gradle
kotlin.code.style=official

# See https://kotlinlang.org/docs/whatsnew2220.html#stable-cross-platform-compilation-for-kotlin-libraries
kotlin.native.enableKlibsCrossCompilation=true
kotlin.native.ignoreDisabledTargets=true

# See https://developer.android.com/jetpack/androidx#using_androidx_libraries_in_your_project
android.useAndroidX=true
android.enableJetifier=true
